name: Check for Merge Conflicts

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  find-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Find merge conflict markers
        uses: olivernybroe/action-conflict-finder@v4.1
        with:
          # Optional: Exclude specific directories or files
          exclude_dir: ".github"
          excludes: "*.lock,*.md"